name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: pnpm/action-setup@v4.0.0
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          cache: pnpm
      - name: Install
        run: pnpm install
      - name: Test
        run: pnpm run test
      - name: Run dev
        run: pnpm run dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
